version: "3.8"

services:

  php:
    build: docker/php
    volumes:
      - .:/var/www/laravel:cached
    working_dir: /var/www/laravel
    environment:
# Laravelの.envはAPP_KEYのみにして、他はここで指定する
      - APP_NAME=PROJECT_NAME (local)
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:NGINX_PORT
      - CACHE_DRIVER=file
      - SESSION_LIFETIME=1
      # @todo; 以降 DB_ はconfig書き換えに変えたい
      - DB_CONNECTION=DATABASE_NAME
      - DB_HOST=DATABASE_NAME
      - DB_PORT=DATABASE_INTERNAL_PORT
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=password
