version: "3.8"

services:

  php:
    build: docker/php
    volumes:
      - .:/var/www/laravel:cached
    working_dir: /var/www/laravel
    mem_limit: 32m
#    mem_limit: "33554432"  # 32MB. local dockerではm, gが使用できない。
#    tty: true
#    stdin_open: true
#    privileged: true
    environment:
# Laravelの.envはAPP_KEYのみにして、他はここで指定する
      - APP_NAME=PROJECT_NAME (local)
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:NGINX_PORT
      - CACHE_DRIVER=file
      - SESSION_LIFETIME=1
      - DB_CONNECTION=DATABASE_NAME
      - DB_HOST=DATABASE_IMAGE
      - DB_PORT=DATABASE_INTERNAL_PORT
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=password

  nginx:
    build: docker/nginx
    ports:
      - "NGINX_PORT:80"
    volumes:
      - .:/var/www/laravel:cached
    working_dir: /var/www/laravel
    mem_limit: 64m
#    mem_limit: "67108864"  # 64MB ギリギリ
    depends_on:
      - php
      - DATABASE_IMAGE
#    stdin_open: true
#    privileged: true

  DATABASE_IMAGE:
    image: DATABASE_IMAGE:DATABASE_VERSION
    ports:
      - "DATABASE_PORT:DATABASE_INTERNAL_PORT" # sequel, pgadmin用
    volumes:
      - "./storage/tmp/local-DATABASE_IMAGE/data:DATABASE_DIR:cached"
      - ./docker/mysql/default.cnf:/etc/mysql/conf.d/default.cnf:cached
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: laravel
#    privileged: true
