version: "3.8"

services:

  php:
    container_name: "PROJECT_NAME-php"
    build: docker/php
    volumes:
      - .:/var/www/PROJECT_NAME:cached
    working_dir: /var/www/PROJECT_NAME
    mem_limit: 32m
#    mem_limit: "33554432"  # 32MB. local dockerではm, gが使用できない。
#    tty: true
#    stdin_open: true
#    privileged: true
    environment:
# Laravelの.envはAPP_KEYのみにして、他はここで指定する
      - APP_NAME=PROJECT_NAME (local)
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:NGINX_PORT
      - CACHE_DRIVER=file
      - SESSION_LIFETIME=1
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=password

  nginx:
    container_name: "PROJECT_NAME-nginx"
    build: docker/nginx
    ports:
      - "NGINX_PORT:80"
    volumes:
      - .:/var/www/PROJECT_NAME:cached
    working_dir: /var/www/PROJECT_NAME
    mem_limit: 64m
#    mem_limit: "67108864"  # 64MB ギリギリ
    depends_on:
      - php
      - mysql
#    stdin_open: true
#    privileged: true

  mysql:
    container_name: "PROJECT_NAME-mysql"
    image: mysql:MYSQL_VERSION
    ports:
      - "MYSQL_PORT:3306" # sequel用
    volumes:
      - "./storage/tmp/local-mysql/data:/var/lib/mysql:cached"
      - ./docker/mysql/default.cnf:/etc/mysql/conf.d/default.cnf:cached
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
#    privileged: true
