(source gnu)
(source melpa)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")



;;; M.Ishikawa
;;; http://qiita.com/aKenjiKato/items/aa8a6d9c797a4f10d9f8

(depends-on "anzu")
(depends-on "auto-install")
(depends-on "expand-region")
(depends-on "highlight-symbol")
(depends-on "multiple-cursors")
(depends-on "wgrep")
(depends-on "exec-path-from-shell")

;; Appearance
(depends-on "molokai-theme")
(depends-on "rainbow-delimiters")
(depends-on "popwin")
(depends-on "yascroll")

;; helm
(depends-on "helm")
(depends-on "helm-git-grep")
(depends-on "helm-gtags")
;(depends-on "helm-ls-git") エラーが出る
(depends-on "helm-themes")

;; progmodes
(depends-on "coffee-mode")
(depends-on "haskell-mode")
(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "markdown-mode")
(depends-on "scala-mode")
(depends-on "tuareg")
(depends-on "web-mode")
(depends-on "yaml-mode")
(depends-on "php-mode")
(depends-on "zencoding-mode")

;;; Ruby
(depends-on "ruby-mode")
(depends-on "ruby-block")
(depends-on "ruby-end")

;; auto-complete.el
(depends-on "auto-complete")
(depends-on "ac-c-headers")
(depends-on "ac-dabbrev")

;; Coding
(depends-on "yasnippet")
(depends-on "flycheck")

;; Git
(depends-on "magit")
(depends-on "git-gutter-fringe+")
(depends-on "git-modes" :git "https://github.com/magit/git-modes.git")

